name: Repository Dispatch

on:
  repository_dispatch:
    types: [build_callback]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Drink Longjing Tea
        run: |
          echo Build Callback:
          echo '  Target:' ${{ github.event.client_payload.target }}
          echo '  Source:' ${{ github.event.client_payload.source }}

